<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-PL81PN6" failures="1" tests="7" name="Test" time="2.241" errors="0" timestamp="2022-08-09T18:33:23 IST">
  <testcase classname="POM.sample1" name="test3" time="0.027"/>
  <testcase classname="POM.sample1" name="test3" time="0.002"/>
  <testcase classname="POM.sample1" name="test2" time="2.02">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method POM.sample1.test2() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method POM.sample1.test2() didn't finish within the time-out 2000
at java.base@18.0.1.1/java.lang.Thread.sleep(Native Method)
at app//POM.sample1.test2(sample1.java:15)
at java.base@18.0.1.1/java.lang.invoke.LambdaForm$DMH/0x0000000800d24000.invokeVirtual(LambdaForm$DMH)
at java.base@18.0.1.1/java.lang.invoke.LambdaForm$MH/0x0000000800d24800.invoke(LambdaForm$MH)
at java.base@18.0.1.1/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
at java.base@18.0.1.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@18.0.1.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@18.0.1.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@18.0.1.1/java.lang.Thread.run(Thread.java:833)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="POM.sample1" name="test1" time="0.0">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="POM.sample" name="test" time="0.002"/>
  <testcase classname="POM.sample" name="test1" time="0.001"/>
  <testcase classname="POM.sample" name="test2" time="0.002"/>
  <testcase classname="POM.sample1" name="test" time="0.0">
    <ignored/>
  </testcase> <!-- test -->
</testsuite> <!-- Test -->
